import React from "react";
import Head from "next/head";
import Header from "./components/admin/pos/Header";
import TopPanel from "./components/admin/pos/TopPanel";
import RightPanel from "./components/admin/pos/RightPanel";
import FooterPanel from "./components/admin/pos/FooterPanel";

const Bill = () => {
  return (
    <div>
      <Head>
        <title>Kiraanaghar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <TopPanel />
      <RightPanel />
      <FooterPanel />
    </div>
  );
};

export default Bill;
