import React from "react";
import Head from "next/head";
import Layout from "../components/admin/Layout/Layout";

const Bill = () => {
  return (
    <div>
      <Head>
        <title>ASA CRM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>bill</Layout>
    </div>
  );
};

export default Bill;
