import React from "react";
import Head from "next/head";
import Layout from "./components/admin/Layout/Layout";

const Settings = () => {
  return (
    <div>
      <Head>
        <title>Kiraanaghar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>Setting</Layout>
    </div>
  );
};

export default Settings;
